import googleapiclient.discovery
from YouTubeSearch import *
from google_auth_oauthlib.flow import InstalledAppFlow

# Name and Description of playlist
playlistName = "AI Generated Playlist"
playlistDescription = "YouTube playlist generated by ChatGPT"

# Define scopes for YouTube Data API (User Data Permissions)
youtubeScopes = ['https://www.googleapis.com/auth/youtube']

# OAuth 2.0 flow
flow = InstalledAppFlow.from_client_secrets_file('client_secret.json', youtubeScopes)
credentials = flow.run_local_server()

# Creating YouTube Data api client for OAUTH
youtubeOAuth = googleapiclient.discovery.build('youtube', 'v3', credentials=credentials)

try:
    # Create the playlist
    playlistResponse = youtubeOAuth.playlists().insert(
        part = 'snippet',
        body = {
            'snippet':{
                'title': playlistName,
                'description': playlistDescription
            }
        }
    ).execute()

    # Grab playlist ID from response
    playlistId = playlistResponse['id']

    tempId = "Yq6qkq_TWAM"

    # Add videos to the playlist
    for id in youtubeIds:
        videoInsert = youtubeOAuth.playlistItems().insert(
            part = 'snippet',
            body = {
                'snippet': {
                    'playlistId': playlistId,
                    'resourceId': {
                        'kind': 'youtube#video',
                        'videoId': id
                    }
                }
            }
        ).execute()
except Exception as e:
    print (f"An error occured: {e}")